//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('match')
export class matchEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  matchId: number;

  @Column('date', { nullable: true })
  date: Date;

  @Column('date', { nullable: true })
  time: Date;

  @Column('text', { nullable: true })
  matchType: string;

  @Column('integer', { nullable: true })
  teamAId: number;

  @Column('integer', { nullable: true })
  teamBId: number;

  @Column('text', { nullable: true })
  status: string;
}
