//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('users')
export class usersEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  userId: number;

  @Column('text', { nullable: true })
  userName: string;

  @Column('text', { nullable: true })
  userPic: string;

  @Column('text', { nullable: true })
  userPhone: string;

  @Column('integer', { nullable: true })
  userPoints: number;
}
