//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const matchTitle = () => {
  const record = useRecordContext();
  return <span>match {record ? `"${record.matchId}"` : ''}</span>;
};

export const matchList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="matchId" />
      <DateField source="date" />
      <DateField source="time" />
      <TextField source="matchType" />
      <ReferenceField source="teamAId" reference="teamsSport" />
      <ReferenceField source="teamBId" reference="teamsSport" />
      <TextField source="status" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const matchEdit = () => (
  <Edit title={<matchTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="matchId" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="matchType" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="teamAId" reference="teamsSport" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="teamBId" reference="teamsSport" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const matchCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="matchId" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="date" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="time" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="matchType" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="teamAId" reference="teamsSport" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="teamBId" reference="teamsSport" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="status" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  <ReferenceInput
    source="teamAId"
    label="teamAId"
    reference="teamsSport"
    alwaysOn
  />,
  <ReferenceInput
    source="teamBId"
    label="teamBId"
    reference="teamsSport"
    alwaysOn
  />,
  ,
];
